### PR TITLE
Added my Registration App

### PR DESCRIPTION
**Pull request by Ash0069**

### CODE REVIEW

**Comment by kanha-gupta** [comment]
@Ash0069 can you please add tech stack ? Thank you

**Comment by kanha-gupta** [comment]
@Ash0069 also please rename file to something like "form_registrationApp"

**Comment by Ash0069** [comment]
should I just tech stack by mentioning them in description or some other way?

**Comment by kanha-gupta** [comment]
> should I just tech stack by mentioning them in description or some other way?

mention it either below or above the description of project

**Comment by Ash0069** [comment]
ok I am creating a new pull request

**Pull request closed without merging**
