### PR TITLE
GFG_POTD_Solution

### PR DESCRIPTION
**Pull request by Gyanthakur**
it contains all problem solutions in C++ which come in GeeksForGeeks platform's daily problem(POTD).

### CODE REVIEW

**Comment by kanha-gupta** [comment]
@Gyanthakur this is a repository for projects & therefore This is not a right repo for GeeksforGeeks solutions :)
Other projects are great !

**Comment by Gyanthakur** [comment]
> @Gyanthakur this is a repository for projects & therefore This is not a right repo for GeeksforGeeks solutions :)
> Other projects are great !

Ohk thankyou

**Comment by kanha-gupta** [comment]
> > @Gyanthakur this is a repository for projects & therefore This is not a right repo for GeeksforGeeks solutions :)
> > Other projects are great !
> 
> Ohk thankyou

Can you please remove it ? Also music player documentation has been added previously so please remove it as well :)

**Comment by Gyanthakur** [comment]
> > > @Gyanthakur this is a repository for projects & therefore This is not a right repo for GeeksforGeeks solutions :)
> > > Other projects are great !
> > 
> > 
> > Ohk thankyou
> 
> Can you please remove it ? Also music player documentation has been added previously so please remove it as well :)

sure

**Pull request merged**
